backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "design"
    label: "Design"
    folder: "src/content/design"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication Date", name: "pubDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
      - { label: "Alt Text", name: "altText", widget: "string", required: false }
      - { label: "Text", name: "text", widget: "markdown" }
      - 
        label: "Images"
        name: "images"
        widget: "list"
        required: false
        field:
          { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Copyright", name: "copyright", widget: "string", required: false }

  - name: "motion-design"
    label: "Motion Design"
    folder: "src/content/motion-design"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication Date", name: "pubDate", widget: "datetime" }
      - { label: "Text", name: "text", widget: "markdown", required: false }
      - 
        label: "Images"
        name: "images"
        widget: "list"
        required: false
        field:
          { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }

  - name: "photography"
    label: "Photography"
    folder: "src/content/photography"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication Date", name: "pubDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
      - { label: "Alt Text", name: "altText", widget: "string", required: false }
      - { label: "Text", name: "text", widget: "markdown", required: false }
      - 
        label: "Images"
        name: "images"
        widget: "list"
        required: false
        field:
          { label: "Image", name: "image", widget: "image" }